name: Metrics
on:
  schedule:
    - cron: '0 23 * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:


jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Rotate Art
        run: python rotate_art.py

      - name: Commit rotated art to README
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Rotate ASCII art [$(date)]"
          git pull --rebase origin main
          git push

      - name: Install dependencies
        run: pip install aiohttp lxml loguru python-dateutil

      - name: Generate metrics
        run: python metrics/today.py
        env:
          ACCESS_TOKEN: ${{ secrets.METRICS_ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.METRICS_USER_NAME }}
          LASTFM_TOKEN: ${{ secrets.LASTFM_TOKEN }}
          LASTFM_USER: ${{ secrets.LASTFM_USER }}
          EXCLUDED_REPOS: ${{ secrets.METRICS_EXCLUDED_REPOS }}
          EXCLUDED_LANGUAGES: "Python, Swift, Jinja, Go, Makefile"

      - name: Commit and push metrics
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dark_mode.svg light_mode.svg cache/
          git diff --staged --quiet || (git commit -m "Update GitHub metrics [$(date)]" && git push)
