name: Metrics
on:
  schedule:
    - cron: '0 23 * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:


jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Rotate Art
        run: python rotate_art.py

      - name: Commit rotated art to README
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Rotate ASCII art [$(date)]"
          git pull --rebase origin main
          git push

      - name: Generate and commit metrics
        uses: xxspell/metrics-generator@main
        with:
          target_repository: lordradez23/lordradez23
          target_branch: main
          access_token: ${{ secrets.METRICS_ACCESS_TOKEN }}
          user_name: ${{ secrets.METRICS_USER_NAME }}
          lastfm_token: ${{ secrets.LASTFM_TOKEN }}
          lastfm_user: ${{ secrets.LASTFM_USER }}
          excluded_repos: ${{ secrets.METRICS_EXCLUDED_REPOS }}
          git_user_name: "GitHub Action"
          git_user_email: "action@github.com"
